### PR TITLE
fang 2010, spectrum choosing

### PR DESCRIPTION
**Pull request by julesvanirsel**
options for changing impact ionization spectra, kappe, accelerated, bi-maxellian

### CODE REVIEW

**Comment by mattzett** [comment]
Thanks for putting this in; I have a few conflicts to look through but I'll definitely get to this soon.

**Comment by julesvanirsel** [comment]
That's great, thank you. excited to see it working. If you have the bandwidth, maybe there's a better way to do the energy binning?

Right now i hard code lbins=64 and have these limits:

do k=1,lbins
  !! energy bin limits
  bin_lb = -1 ! lower limit from Fang 2008, 2010
  select case (diff_num_flux)
  case (0) ! Maxwellian
    bin_ub = log10(20*E0_keV) ! gives 1.12e-7 x max(phi)
  case (3) ! accelerated Maxwellian
    bin_ub = log10(20*E0_keV)
  case (4) ! Evans, D. S. (1974) 2 keV acc., 0.8 keV temp
    bin_ub = log10(10*2.0_wp)
  case default
    bin_ub = 3 ! upper limit from Fang 2008, 2010
  end select

where energy goes logarithmically from 10^bin_lb to 10^bin_ub (linear in exponent)

Jules
________________________________________________
Jules van Irsel (He/Him/His)
Graduate Student
Department of Physics and Astronomy, Dartmouth College
6127 Wilder Laboratory, Room 317
Hanover, NH 03755
C: (603) 266 8084
E: ***@***.***
________________________________

**Comment by mattzett** [comment]
Here what we might consider doing is just passing in the full cfg structure to ionrate_fang so that additional parameters could, in principle be added to the ionization calculations.  

```
<<<<<<< HEAD
      Prprecip=0.0; Qeprecip=0.0;
      !! Fang et al 2008 parameterization
      do iprec=1,lprec
        !! loop over the different populations of precipitation (2 here?), accumulating production rates
        Prpreciptmp = ionrate_fang(W0(:,:,iprec), PhiWmWm2(:,:,iprec), nn, Tn, cfg%flag_fang, x%g1)
        !! calculation based on Fang et al [2008]
=======
      !! Fang et al 2008/2010 parameterization
      do iprec=1,lprec
        !! loop over the different populations of precipitation (2 here?), accumulating production rates
        if (iprec==1) then ! background precipitation is hard-coded Fang et al. 2008 maxwellian
          Prpreciptmp = ionrate_fang(W0(:,:,iprec), PhiWmWm2(:,:,iprec), x%alt, nn, Tn, x%g1 &
            , 2008, cfg%diff_num_flux, cfg%kappa, cfg%bimax_frac, cfg%W0_char)
        else ! any additional precipitation populations parameters are chosen by the user
          Prpreciptmp = ionrate_fang(W0(:,:,iprec), PhiWmWm2(:,:,iprec), x%alt, nn, Tn, x%g1 &
            , cfg%flag_fang, cfg%diff_num_flux, cfg%kappa, cfg%bimax_frac, cfg%W0_char)
        end if
        !! calculation based on Fang et al [2008,2010]
>>>>>>> 2abc2968 (work in progress.)
        Prprecip=Prprecip+Prpreciptmp
      end do      
```

**Comment by mattzett** [comment]
@julesvanirsel Can you add me to your fork so I can push some partial merge steps?

**Comment by julesvanirsel** [comment]
Alright, and let me look into this, it's been a while since I looked at this

Thank you!
Jules

________________________________________________
Jules van Irsel (He/Him/His)
Graduate Student
Department of Physics and Astronomy, Dartmouth College
6127 Wilder Laboratory, Room 317
Hanover, NH 03755
C: (603) 266 8084
E: ***@***.***
________________________________

**Comment by mattzett** [comment]
I'm working on the merged version here:  https://github.com/julesvanirsel/gemini3d/tree/MZ_upstream_merge2

**Pull request closed without merging**
